# Generated by Django 4.2.11 on 2026-03-07 12:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "停用"), (1, "启用"), (2, "已删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="工号"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "超级管理员"),
                            (1, "管理员"),
                            (2, "库存管理员"),
                            (3, "财务人员"),
                            (4, "收银员"),
                        ],
                        default=4,
                        verbose_name="角色",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="手机号码格式不正确，应为11位数字并以1开头", regex="^1[3-9]\\d{9}$"
                            )
                        ],
                        verbose_name="手机号",
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "男"), (1, "女"), (2, "未知")],
                        default=2,
                        verbose_name="性别",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="部门"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="职位"
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="最后登录IP"
                    ),
                ),
                (
                    "last_login_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后登录时间"),
                ),
                (
                    "password_changed_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="密码修改时间"),
                ),
                (
                    "login_failures",
                    models.IntegerField(default=0, verbose_name="登录失败次数"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="锁定至"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户管理",
                "ordering": ["-date_joined"],
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="组名"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="组代码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "permissions",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON格式的权限列表",
                        verbose_name="权限列表",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "停用"), (1, "启用"), (2, "已删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="组成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户组",
                "verbose_name_plural": "用户组管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "status"], name="users_user_role_6e67fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["department", "status"], name="users_user_departm_adf05e_idx"
            ),
        ),
    ]
