# Generated by Django 4.2.11 on 2026-03-07 12:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "order_no",
                    models.CharField(
                        db_index=True,
                        help_text="系统自动生成：IN-年月日-流水号",
                        max_length=50,
                        unique=True,
                        verbose_name="入库单号",
                    ),
                ),
                (
                    "in_type",
                    models.IntegerField(
                        choices=[
                            (1, "采购入库"),
                            (2, "退货入库"),
                            (3, "生产入库"),
                            (4, "调拨入库"),
                            (99, "其他"),
                        ],
                        default=1,
                        verbose_name="入库类型",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="总金额",
                    ),
                ),
                (
                    "in_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="入库日期"
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="发票号"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "草稿"),
                            (1, "待审核"),
                            (2, "已审核"),
                            (3, "已完成"),
                            (4, "已取消"),
                        ],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ins",
                        to="products.supplier",
                        verbose_name="供货商",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ins",
                        to="products.warehouse",
                        verbose_name="入库仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "入库单",
                "verbose_name_plural": "入库单管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="StockOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "order_no",
                    models.CharField(
                        db_index=True,
                        help_text="系统自动生成：OUT-年月日-流水号",
                        max_length=50,
                        unique=True,
                        verbose_name="出库单号",
                    ),
                ),
                (
                    "out_type",
                    models.IntegerField(
                        choices=[
                            (1, "销售出库"),
                            (2, "退货给供货商"),
                            (3, "报损出库"),
                            (4, "调拨出库"),
                            (99, "其他"),
                        ],
                        default=1,
                        verbose_name="出库类型",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="总金额",
                    ),
                ),
                (
                    "out_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="出库日期"
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="客户"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "草稿"),
                            (1, "待审核"),
                            (2, "已审核"),
                            (3, "已完成"),
                            (4, "已取消"),
                        ],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_outs",
                        to="products.warehouse",
                        verbose_name="出库仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "出库单",
                "verbose_name_plural": "出库单管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="StockInDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="数量",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="单价",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="金额",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="批次号"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="过期日期"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_in_details",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "stock_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="operations.stockin",
                        verbose_name="入库单",
                    ),
                ),
            ],
            options={
                "verbose_name": "入库明细",
                "verbose_name_plural": "入库明细管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="SalesStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_date",
                    models.DateField(db_index=True, unique=True, verbose_name="统计日期"),
                ),
                ("sale_quantity", models.IntegerField(default=0, verbose_name="销售数量")),
                (
                    "sale_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="销售金额"
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="采购成本"
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="毛利",
                    ),
                ),
                (
                    "gross_margin",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        editable=False,
                        help_text="百分比，如0.15表示15%",
                        max_digits=5,
                        verbose_name="毛利率",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_stats",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售统计",
                "verbose_name_plural": "销售统计管理",
                "ordering": ["-stat_date"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.IntegerField(
                        choices=[
                            (1, "登录"),
                            (2, "登出"),
                            (3, "创建"),
                            (4, "更新"),
                            (5, "删除"),
                            (6, "导入"),
                            (7, "导出"),
                            (8, "审核"),
                            (9, "驳回"),
                            (99, "其他"),
                        ],
                        verbose_name="操作类型",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="操作对象")),
                (
                    "object_id",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="对象ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="对象描述"
                    ),
                ),
                (
                    "action_detail",
                    models.TextField(blank=True, default="", verbose_name="操作详情"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="用户代理"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="操作时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="CashierData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "停用"), (1, "启用"), (2, "已删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "transaction_id",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="交易号"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="数量",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="单价",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="金额",
                    ),
                ),
                ("transaction_time", models.DateTimeField(verbose_name="交易时间")),
                (
                    "import_batch",
                    models.CharField(db_index=True, max_length=50, verbose_name="导入批次"),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="是否已生成出库记录", verbose_name="已处理"
                    ),
                ),
                (
                    "processed_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        limit_choices_to={"role": 4},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashier_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收银员",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashier_data",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "收银数据",
                "verbose_name_plural": "收银数据管理",
                "ordering": ["-transaction_time"],
            },
        ),
        migrations.CreateModel(
            name="StockOutDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="数量",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="单价",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="金额",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_out_details",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "stock_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="operations.stockout",
                        verbose_name="出库单",
                    ),
                ),
            ],
            options={
                "verbose_name": "出库明细",
                "verbose_name_plural": "出库明细管理",
                "ordering": ["-create_time"],
                "unique_together": {("stock_out", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="stockout",
            index=models.Index(
                fields=["order_no"], name="operations__order_n_6dec44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockout",
            index=models.Index(
                fields=["out_type", "status"], name="operations__out_typ_faa12a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockout",
            index=models.Index(
                fields=["warehouse", "status"], name="operations__warehou_8a2fe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockout",
            index=models.Index(
                fields=["out_date", "status"], name="operations__out_dat_37f246_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockindetail", unique_together={("stock_in", "product")},
        ),
        migrations.AddIndex(
            model_name="stockin",
            index=models.Index(
                fields=["order_no"], name="operations__order_n_468a7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockin",
            index=models.Index(
                fields=["supplier", "status"], name="operations__supplie_e2b9f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockin",
            index=models.Index(
                fields=["warehouse", "status"], name="operations__warehou_6fdc33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockin",
            index=models.Index(
                fields=["in_date", "status"], name="operations__in_date_106f60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesstat",
            index=models.Index(
                fields=["stat_date", "product"], name="operations__stat_da_03744e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesstat", unique_together={("stat_date", "product")},
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(
                fields=["user", "create_time"], name="operations__user_id_6c6e24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(
                fields=["action_type", "create_time"],
                name="operations__action__30d953_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(
                fields=["model_name", "create_time"],
                name="operations__model_n_6362d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashierdata",
            index=models.Index(
                fields=["transaction_id"], name="operations__transac_88b765_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashierdata",
            index=models.Index(
                fields=["import_batch", "is_processed"],
                name="operations__import__630d3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashierdata",
            index=models.Index(
                fields=["transaction_time"], name="operations__transac_c636b7_idx"
            ),
        ),
    ]
