# Generated by Django 4.2.11 on 2026-03-07 12:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "停用"), (1, "启用"), (2, "已删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "level",
                    models.IntegerField(default=1, editable=False, verbose_name="层级"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="为空表示一级分类",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.category",
                        verbose_name="父分类",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类管理",
                "ordering": ["level", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "停用"), (1, "启用"), (2, "已删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("address", models.TextField(verbose_name="仓库地址")),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="单位：立方米",
                        max_digits=10,
                        null=True,
                        verbose_name="仓库容量",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": [0, 1, 2]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="仓库管理员",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "停用"), (1, "启用"), (2, "已删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("contact_person", models.CharField(max_length=50, verbose_name="联系人")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("address", models.TextField(verbose_name="地址")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="税号"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="银行账号"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="开户行"
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "供货商",
                "verbose_name_plural": "供货商管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "停用"), (1, "启用"), (2, "已删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "barcode",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="条形码"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "件"),
                            ("box", "箱"),
                            ("bag", "袋"),
                            ("bottle", "瓶"),
                            ("kg", "千克"),
                            ("g", "克"),
                            ("L", "升"),
                            ("ml", "毫升"),
                            ("m", "米"),
                        ],
                        default="piece",
                        max_length=20,
                        verbose_name="单位",
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如：500g/袋",
                        max_length=100,
                        verbose_name="规格",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="单位：元",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="进价",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="单位：元",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="售价",
                    ),
                ),
                (
                    "min_stock",
                    models.IntegerField(
                        default=0, help_text="库存预警阈值", verbose_name="最低库存"
                    ),
                ),
                (
                    "max_stock",
                    models.IntegerField(
                        blank=True, help_text="最大库存容量", null=True, verbose_name="最高库存"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="品牌"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="生产商"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "expiry_days",
                    models.IntegerField(
                        blank=True,
                        help_text="从生产日期起计算",
                        null=True,
                        verbose_name="保质期天数",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                        verbose_name="商品分类",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.supplier",
                        verbose_name="默认供货商",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_stock", models.IntegerField(default=0, verbose_name="当前库存")),
                (
                    "locked_stock",
                    models.IntegerField(
                        default=0, help_text="已被订单锁定但未出库的数量", verbose_name="锁定库存"
                    ),
                ),
                (
                    "available_stock",
                    models.IntegerField(default=0, editable=False, verbose_name="可用库存"),
                ),
                (
                    "warning_sent",
                    models.BooleanField(default=False, verbose_name="已发送预警"),
                ),
                (
                    "last_inventory_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后盘点时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="products.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品库存",
                "verbose_name_plural": "商品库存管理",
                "ordering": ["-update_time"],
                "indexes": [
                    models.Index(
                        fields=["product", "warehouse"],
                        name="products_pr_product_cd17ff_idx",
                    ),
                    models.Index(
                        fields=["available_stock"],
                        name="products_pr_availab_2f7337_idx",
                    ),
                ],
                "unique_together": {("product", "warehouse")},
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="products_pr_categor_75eeb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="products_pr_barcode_e44f4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["supplier", "status"], name="products_pr_supplie_201d34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "status"], name="products_ca_parent__70e571_idx"
            ),
        ),
    ]
